name: pages build and deployment

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: mkdir build
      - uses: docker://pandoc/core:2.9
        with:
          args: >-
            --standalone
            --output=build/index.html
            data.md
      - run: touch artifact.tar && tar --dereference --hard-dereference -cvf artifact.tar build
      - uses: actions/upload-artifact@main
        with:
          name: github-pages
          path: ./artifact.tar
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v1-beta
