name: pages build and deployment

on: [push]

permissions:
  contents: read
  id-token: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - run: mkdir build
      - name: Build
        uses: docker://pandoc/core:2.9
        with:
          args: >-
            --standalone
            --output=build/index.html
            data.md
      - name: Archive build output
        run: tar --dereference --hard-dereference --directory build/ -cvf artifact.tar .
      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: github-pages
          path: ./artifact.tar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
