name: pages build and deployment

on: [push]

permissions:
  contents: read
  metadata: read
  pages: write
  # via https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers
  id-token: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - run: mkdir build
      - name: Build
        uses: docker://pandoc/core:2.9
        with:
          args: >-
            --standalone
            --output=build/index.html
            data.md
      - name: Archive build output
        run: touch artifact.tar && tar --dereference --hard-dereference -cvf artifact.tar build
      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: github-pages
          path: ./artifact.tar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1-beta
